MemoTesi, LateX thesis template
csunibo/latex-thesis pull request #3
Opened 2023-06-11 08:44 UTC by AndreSkin

MemoTesi, LateX thesis template with simple commands explained

2023-06-11 10:43 UTC, foxyseta requested changes
Richiederò anche la recensione di @lucat1 e altra gente in procinto di finire la tesi.

2023-06-11 10:43 UTC, foxyseta commented on MemoTesi/result/MemoTesi.pdf
Questo file è binario autogenerato, e quindi non va committato su git. Va rimosso.

2023-06-11 10:43 UTC, foxyseta commented on MemoTesi/main.tex
> +Per riferirti a qualcosa basta fare ref seguito dal nome della label, ad esempio "vedi capitolo \ref{chap:intro}".\\In questo modo dal pdf cliccando sulla reference, ti porta direttamente al punto gi
Per le virgolette su LaTeX usare `` in apertura e '' in chiusura, o vengono tipograficamente sbagliate.
```suggestion
Per riferirti a qualcosa basta fare ref seguito dal nome della label, ad esempio ``vedi capitolo \ref{chap:intro}''.\\In questo modo dal pdf cliccando sulla reference, ti porta direttamente al punto giusto.
```

2023-06-11 10:43 UTC, foxyseta commented on MemoTesi/main.tex
> +Per citare si usa cite seguito dal nome dell'articolo nel file.bib, ad esempio "come visto nell'articolo di tizio\cite{greenwade93}".
Per le virgolette su LaTeX usare `` in apertura e '' in chiusura, o vengono tipograficamente sbagliate.
```suggestion
Per citare si usa cite seguito dal nome dell'articolo nel file.bib, ad esempio ``come visto nell'articolo di tizio\cite{greenwade93}''.
```

2023-06-11 10:43 UTC, foxyseta commented on MemoTesi/main.tex
`main.tex` non può essere un file a sé stante, o tutte le persone devono pescarne i contenuti quando lavorano sul file principale. I suoi contenuti dovrebbero essere inseriti in mezzo a `tesi/tesi.tex`.

2023-06-11 10:43 UTC, foxyseta commented on MemoTesi/README.txt
Da rimuovere. Duplicato del README principale.

2023-06-11 10:43 UTC, foxyseta commented on MemoTesi/MemoTesi.zip
Da rimuovere. Duplicato di contenuti della _repository_. Inoltre essendo in formato binario git non può tracciarlo altrettanto bene rispetto alle controparti non compresse.

2023-06-11 11:58 UTC, lucat1 requested changes
Solo qualche consiglio extra che aggiungerei. Per il resto una volta sistemato quello che ha segnalato @foxyseta va bene imo.

2023-06-11 11:58 UTC, lucat1 commented on MemoTesi/main.tex
> +Attenzione però che ogni tanto questa feature fa lasciare troppo spazio tra testo e immagini / tabelle, se capita prova a togliere un po' di righe vuote.
Spiegherei che cambia il modo in cui vengono impaginati i `\n\n` e che è un buon trick per allungare di qualche pagina il documento ;).
```suggestion
Attenzione però che ogni tanto questa feature fa lasciare troppo spazio tra testo e immagini / tabelle, se capita prova a togliere un po' di righe vuote. Senza questo pacchetto, una doppia new line (\texttt{\n\n}) creea un nuovo paragrafo, la cui prima riga viene leggermente indentata (un comportamento indesiderato se vieni da altri strumenti di stesura). Eventualmente, si può usare per allungare di qualche pagina alla tesi, evitando di abusarne.
```

2023-06-11 11:58 UTC, lucat1 commented on MemoTesi/main.tex
> +
Direi due parole anche su altri pacchetti per creare le reference che automatizzano la cosa e levano margine di errore:
```suggestion
Altri pacchetti come \texttt{fancyref} e \texttt{cleveref} (consigliato) possono aiutare nell'automatizzare la creazione delle refrence. Usando ad esempio \texttt{\cref{chap:intro}} viene generata la dicitura corrispondete all'elemento a cui si fa riferimento, seguita dalla numerazione. Eccone un esempio: \cref{chap:intro}.
```

2023-06-11 11:58 UTC, lucat1 commented on MemoTesi/main.tex
> +\usepackage{hyperref}
Aggiungiamo per l'esempio successivo il pacchetto `cleveref`:
```suggestion
\usepackage{hyperref}
\usepackage[capitalize,noabbrev]{cleveref}
```

2023-06-12 07:09 UTC, AndreSkin commented on MemoTesi/main.tex
Fatto, ho aggiunto embed di pdf, url, landscape, appendici, math mode, footnote e bibliografia alternativa

2023-06-12 09:32 UTC, lucat1 approved these changes

2023-06-12 09:34 UTC, merged

2023-06-12 10:16 UTC, gabrielegenovese commented
Forse si potrebbe fare un esempio di un file tex importato. Io lo uso per avere i capitoli divisi in file diversi, ma non starei a riaprire la pr per sta roba. Per il resto, buoni i commenti nuovi e bibtex.

2023-06-12 13:25 UTC, foxyseta commented
Siii pure io uso i tex diversi ma siccome abbiamo già mergiato aprire una issue distinta. A @kocierik penso servissero pure esempio di listing di codice